# RBAC Role Configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: fullstackenabler
  name: nginx-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
# RoleBinding Configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-rolebinding
  namespace: fullstackenabler
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: fullstackenabler
roleRef:
  kind: ClusterRoleRole
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io

---
# Nginx Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
# Service Account Configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: fullstackenabler
