apiVersion: v1
kind: Namespace
metadata:
  name: fullstackenabler

---
# RBAC Role Configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fse-ngx-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]

---
# RoleBinding Configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fse-ngx-rolebinding
subjects:
  - kind: Group
    name: fse-user-aliases
  - kind: ServiceAccount
    name: nginx-sa
    namespace: fullstackenabler
roleRef:
  kind: ClusterRole
  name: fse-ngx-role
  apiGroup: rbac.authorization.k8s.io

---
# Nginx Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fse-ngx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
# Service Account Configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: fullstackenabler
