apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdm-devops
rules:
  # General pod and deployment management
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Cluster-wide information access
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "events"]
    verbs: ["get", "list", "watch"]

  # Role and policy inspection
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]

  # Ability to impersonate users and service accounts
  - apiGroups: [""]
    resources: ["users", "serviceaccounts"]
    verbs: ["impersonate"]

  - apiGroups: ["authentication.k8s.io"]
    resources: ["userextras/scopes"]
    verbs: ["impersonate"]

  # Allow managing persistent volume claims (PVCs)
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow scaling deployments and statefulsets
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update"]

  # Allow exec into running pods for debugging
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
