apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sdm-devops-binding
subjects:
  - kind: Group
    name: sdm-devops  # Bind the entire group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sdm-devops
  apiGroup: rbac.authorization.k8s.io
