apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478603337655:role/SDMenable-eks-node
      username: sdmenable_user
      groups:
        - system:bootstrappers
        - system:nodes
